-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Creato il: Gen 29, 2026 alle 13:42
-- Versione del server: 10.4.32-MariaDB
-- Versione PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--Database: `moodread_progetto`
-- --------------------------------------------------------

CREATE TABLE `libri_biblioterapia` (
  `id` int(11) NOT NULL,
  `titolo` varchar(255) NOT NULL,
  `autore` varchar(150) DEFAULT NULL,
  `citazione` text DEFAULT NULL,
  `descrizione` text DEFAULT NULL,
  `cover_image` varchar(500) DEFAULT NULL,
  `emozione_target` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


INSERT INTO `libri_biblioterapia` (`id`, `titolo`, `autore`, `citazione`, `descrizione`, `cover_image`, `emozione_target`) VALUES
(1, 'L\'istituto', 'Stephen King', '\"L\'Istituto è come il motel di un film dell\'orrore. Chi prende una stanza non ne esce più.\"', '\"Nel cuore della notte, Luke Ellis viene rapito e i suoi genitori assassinati. Si risveglia nell\'Istituto, una struttura segreta nascosta nei boschi del Maine, dove bambini dotati di poteri speciali come telepatia e telecinesi vengono imprigionati e sottoposti a esperimenti crudeli per scopi oscuri. Luke dovrà trovare un modo per fuggire da un luogo da cui nessuno è mai scappato.\"', '/covers/istituto.jpg', 'carico'),
(2, 'Shining', 'Stephen King', '\"I mostri sono reali, e anche i fantasmi sono reali. Vivono dentro di noi e, a volte, vincono.\"', '\"Jack Torrance, scrittore in crisi ed ex alcolista, accetta il lavoro di guardiano invernale all\'Overlook Hotel, un albergo isolato tra le montagne del Colorado. Si trasferisce lì con la moglie Wendy e il figlio Danny, dotato di misteriosi poteri extrasensoriali chiamati \'luccicanza\' (shining). Mentre la neve blocca ogni via di fuga, le forze oscure dell\'hotel iniziano a possedere la mente di Jack, trasformandolo in una minaccia mortale per la sua stessa famiglia.\"', '/covers/shining.jpg', 'carico'),
(3, 'IT', 'Stephen King', '\"Forse non esistono i buoni amici o i cattivi amici. Forse ci sono solo amici, persone che ti stanno accanto quando ti fai male e che ti aiutano a non sentirti solo. Forse ne vale sempre la pena di avere paura per loro.\"', '\"A Derry, nel Maine, una piccola città apparentemente tranquilla, un\'antica forza malvagia si risveglia ogni 27 anni per nutrirsi delle paure dei bambini. Sette ragazzini emarginati, uniti nel \'Club dei Perdenti\', devono affrontare i loro peggiori incubi per combattere Pennywise, il clown danzante, in una promessa di sangue che li richiamerà a casa anche da adulti.\"', '/covers/it.jpg', 'carico'),
(4, 'Divergent', 'Veronica Roth', '\"Una scelta può trasformarti. Una scelta può distruggerti. Una scelta ti definisce.\"', '\"In una Chicago distopica, la società è divisa in cinque fazioni consacrate ognuna a una virtù diversa. Beatrice \'Tris\' Prior scopre di essere una Divergente, qualcuno che non appartiene a nessun gruppo e per questo considerata pericolosa. Mentre cerca di nascondere la sua natura, scopre un complotto per distruggere tutti i Divergenti e dovrà scegliere da che parte stare prima che sia troppo tardi.\"', '/covers/divergent.jpg', 'carico'),
(5, 'Allegiant', 'Veronica Roth', '\"Siamo persone danneggiate. Non siamo perfetti. Ma ci ripariamo a vicenda. Ci guariamo a vicenda.\"', '\"Il sistema delle fazioni è crollato e la città è nel caos. Tris e Tobias decidono di varcare la recinzione che circonda Chicago per scoprire la verità su ciò che c\'è fuori. Si ritroveranno di fronte a una realtà sconvolgente che metterà in discussione tutto ciò in cui hanno sempre creduto, costringendoli a scelte impossibili tra amore, lealtà e sacrificio.\"', '/covers/allegiant.jpg', 'carico'),
(6, 'Insurgent', 'Veronica Roth', '\"La verità è come un animale selvaggio, è troppo potente per rimanere in gabbia.\"', '\"La guerra è ormai scoppiata tra le fazioni. Tris cerca disperatamente alleati mentre fugge dalla fazione degli Eruditi guidata da Jeanine Matthews. Ma oltre ai nemici esterni, deve combattere i suoi demoni interiori: il dolore per la perdita dei genitori e il terribile senso di colpa per aver ucciso un amico. Per salvare ciò che resta del suo mondo, dovrà scoprire la verità sul passato della sua famiglia.\"', '/covers/insurgent.jpg', 'carico'),
(7, 'It Ends with Us', 'Colleen Hoover', '\"Non esistono persone cattive. Siamo tutti persone che, qualche volta, fanno cose cattive.\"', '\"Lily Bloom si è appena trasferita a Boston per inseguire il suo sogno di aprire un negozio di fiori. L\'incontro casuale con l\'affascinante neurochirurgo Ryle Kincaid sembra l\'inizio di una favola, ma la loro relazione intensa porta a galla lati oscuri di Ryle che ricordano a Lily un passato doloroso. Quando il suo primo amore, Atlas Corrigan, riappare improvvisamente nella sua vita, Lily si troverà di fronte a una scelta difficile e dolorosa per spezzare il ciclo della violenza.\"', '/covers/itendswithus.jpg', 'innamorato'),
(8, 'Il cavaliere d\'inverno', 'Paullina Simons', '\"Tu sei il mio respiro, Tatiana. Senza di te non esisto.\"', '\"Leningrado, 1941. Mentre le armate tedesche avanzano e l\'inverno minaccia di distruggere la città, la giovane Tatiana incontra Alexander, un misterioso ufficiale dell\'Armata Rossa. Tra loro nasce un amore proibito e travolgente che dovrà sopravvivere alla fame, alla guerra e ai terribili segreti che Alexander nasconde, in una lotta disperata contro il destino e la morte.\"', '/covers/ilcavalieredinverno.jpg', 'innamorato'),
(9, 'Sette mariti di Evelyn Hugo', 'Taylor Jenkins Reid', '\"Ho passato metà del mio tempo ad amarla e l\'altra metà a nascondere quanto l\'amassi.\"', '\"Evelyn Hugo, leggendaria icona di Hollywood ormai anziana e reclusa, decide finalmente di dire la verità sulla sua vita scandalosa e sui suoi sette matrimoni. Sceglie una sconosciuta reporter, Monique Grant, per scrivere la sua biografia. Ma mentre le storie dei mariti si susseguono, emerge il vero segreto di Evelyn: un amore proibito, intenso e struggente che ha attraversato decenni, l\'unico per cui valeva davvero la pena lottare.\"', '/covers/isettemaritidievelynhugo.jpg', 'innamorato'),
(10, 'Chiamami col tuo nome', 'André Aciman', '\"Strappiamo via così tanto di noi stessi per guarire in fretta dalle ferite che finiamo in bancarotta a trent\'anni... Ma non provare nulla, per non provare nulla, è uno spreco enorme.\"', '\"In una calda estate della Riviera ligure a metà anni Ottanta, il diciassettenne Elio trascorre le giornate tra musica, libri e nuotate. L\'arrivo di Oliver, un ventiquattrenne americano ospite di suo padre per sei settimane, sconvolge la sua tranquillità. Tra i due nasce un\'attrazione improvvisa e travolgente, fatta di sguardi, silenzi e un desiderio che li cambierà per sempre. Un racconto struggente sull\'intensità del primo amore e sulla paura di perdere l\'attimo.\"', '/covers/chiamamicoltuonome.jpg', 'innamorato'),
(11, 'Cime tempestose', 'Emily Brontë', '\"Di qualunque cosa siano fatte le nostre anime, la mia e la sua sono la stessa cosa.\"', '\"Nella desolata e ventosa brughiera dello Yorkshire, si consuma l\'amore selvaggio e distruttivo tra Heathcliff, un trovatello dall\'animo oscuro, e Catherine Earnshaw. Un legame così profondo e ossessivo che nemmeno il matrimonio di lei con un altro uomo, né la morte stessa, riusciranno a spezzare. Heathcliff dedicherà la sua vita a una crudele vendetta, dimostrando che l\'amore può essere la forza più potente e terribile della natura.\"', '/covers/cimetempestose.jpg', 'innamorato'),
(12, 'Anna Karenina', 'Lev Tolstoj', '\"Cercava di non guardarla, come se fosse il sole, ma la vedeva, come il sole, anche senza guardarla.\"', '\"Nella Russia dell\'Ottocento, l\'affascinante e rispettata Anna Karenina sfida le rigide convenzioni sociali abbandonando il marito e il figlio per seguire una passione travolgente per il conte Vronskij. La loro storia d\'amore, intensa e scandalosa, la trascinerà in un vortice di isolamento e disperazione, mostrando il prezzo terribile che a volte si paga per inseguire il proprio cuore.\"', '/covers/annakarenina.jpg', 'innamorato'),
(13, 'L\'amore ai tempi del colera', 'Gabriel García Márquez', '\"«E fino a quando crede che possiamo continuare con questo andirivieni del cazzo?» domandò lei. Florentino Ariza aveva la risposta pronta da cinquantatré anni, sette mesi e undici giorni, notti comprese. «Per tutta la vita» disse.\"', '\"Florentino Ariza si innamora perdutamente di Fermina Daza in gioventù, ma lei sceglie di sposare un ricco medico. Florentino non si arrende: decide di diventare un uomo degno di lei e aspetta pazientemente che il destino li riunisca. Dopo cinquantun anni, nove mesi e quattro giorni di attesa incrollabile, avrà finalmente l\'occasione di rinnovare la sua promessa d\'amore eterno.\"', '/covers/lamoreaitiempidelcolera.jpg', 'innamorato'),
(14, 'Le pagine della nostra vita', 'Nicholas Sparks', '\"L\'amore più bello è quello che risveglia l\'anima e che ci fa desiderare di arrivare più in alto; è quello che incendia il nostro cuore e porta la pace nella nostra mente.\"', '\"In una casa di riposo, un anziano signore legge ogni giorno le pagine di un vecchio diario a una donna che ha perso la memoria. È la storia di Noah e Allie, due ragazzi che si sono amati perdutamente durante un\'estate nella Carolina del Nord e che la guerra e le differenze sociali hanno tentato di dividere. Un racconto commovente sulla forza dei ricordi e su un amore capace di compiere miracoli.\"', '/covers/lepaginedellanostravita.jpg', 'innamorato'),
(15, 'Jane Eyre', 'Charlotte Bronte', '\"Non sono un uccello e non c\'è rete che possa intrappolarmi: sono una creatura umana libera, con una volontà indipendente.\"', '\"Jane, orfana e maltrattata, cresce con una forza d\'animo incrollabile che la porta a diventare istitutrice a Thornfield Hall. Qui incontra il misterioso e tormentato Mr. Rochester, con cui nasce un legame intellettuale e passionale profondo. Ma un terribile segreto nascosto nella soffitta della dimora minaccia di distruggere la loro felicità, costringendo Jane a scegliere tra l\'amore e la propria dignità.\"', '/covers/janeeyre.jpg', 'innamorato'),
(16, 'Il Grande Gatsby', 'F. Scott Fitzgerald', '\"Al tocco delle sue labbra, sbocciò per lui come un fiore e l\'incarnazione fu completa.\"', '\"Nella sfolgorante Età del Jazz, il misterioso milionario Jay Gatsby organizza feste leggendarie nella sua villa a Long Island con un unico, segreto scopo: ritrovare Daisy Buchanan, l\'amore della sua vita perso anni prima. Una storia iconica sull\'ossessione, sulla speranza incrollabile e sul sogno disperato di poter ripetere il passato per riconquistare un amore perduto.\"', '/covers/ilgrandegatsby.jpg', 'innamorato'),
(17, 'Dieci piccoli indiani', 'Agatha Christie', '\"Dieci piccoli indiani andarono a pranzo... e poi non ne rimase nessuno.\"', '\"Dieci sconosciuti vengono invitati, con pretesti diversi, su una lussuosa isola deserta da un misterioso ospite che non si fa vedere. Durante la prima cena, una voce inumana li accusa uno per uno di aver commesso un crimine impunito. Da quel momento, iniziano a morire uno dopo l\'altro, seguendo inquietantemente il testo di un\'antica filastrocca appesa nelle loro camere. Con il terrore che cresce e nessuna via di fuga, i sopravvissuti capiscono una verità agghiacciante: l\'assassino è uno di loro.\"', '/covers/diecipiccoliindiani.jpg', 'ansioso'),
(18, 'Assassinio allo specchio', 'Agatha Christie', '\"Lo specchio si incrinò da parte a parte; «La maledizione è su di me» gridò la Dama di Shalott.\"', '\"La sonnolenta St. Mary Mead è in fermento: la famosa attrice hollywoodiana Marina Gregg si è trasferita nella villa locale. Durante il ricevimento di benvenuto, però, una sua ammiratrice muore improvvisamente dopo aver bevuto un cocktail che sembrava destinato alla diva. Un attimo prima della tragedia, Marina è stata vista fissare il vuoto con un\'espressione di puro terrore, come se avesse visto un fantasma. Spetterà a Miss Marple capire quale oscuro segreto del passato sia tornato a perseguitarla.\"', '/covers/assassinioallospecchio.jpg', 'ansioso'),
(19, 'Assassinio sull\'Orient Express', 'Agatha Christie', '\"L\'impossibile non può essere accaduto, quindi l\'impossibile deve essere possibile, a dispetto delle apparenze.\"', '\"Mentre il lussuoso Orient Express attraversa i Balcani, una tempesta di neve blocca il treno nel cuore della notte. Il mattino seguente, il ricco uomo d\'affari Samuel Ratchett viene trovato morto nel suo scompartimento, pugnalato dodici volte, con la porta chiusa dall\'interno. Isolato dal resto del mondo, Hercule Poirot deve interrogare i passeggeri, scoprendo che l\'assassino è ancora a bordo e che quasi tutti avevano un motivo per volere la vittima morta.\"', '/covers/assassiniosullorientexpress.jpg', 'ansioso'),
(20, 'Il pericolo senza nome', 'Agatha Christie', '\"Quella non era una vespa, Mademoiselle. Era una pallottola.\"', '\"Mentre si gode una vacanza sulla costa della Cornovaglia, Hercule Poirot incontra la giovane Nick Buckley, proprietaria della decadente \'End House\'. La ragazza racconta con leggerezza di essere scampata a tre strani incidenti quasi fatali in pochi giorni. Poirot capisce subito che non si tratta di sfortuna, ma di tentativi di omicidio falliti. Qualcuno vuole Nick morta, e l\'investigatore deve scoprire l\'identità di un assassino invisibile nascosto tra gli amici della ragazza prima che riesca nel suo intento.\"', '/covers/ilpericolosenzanome.jpg', 'ansioso'),
(21, 'La verità sul caso di Harry Quebert', 'Joel Dicker', '\"La vita è una lunga caduta, Marcus. La cosa più importante è saper cadere.\"', '\"Marcus Goldman, giovane scrittore di successo in piena crisi creativa, cerca rifugio nel New Hampshire dal suo mentore, il grande Harry Quebert. La tranquillità viene spazzata via quando il corpo di Nola Kellergan, una ragazza scomparsa trentatré anni prima, viene ritrovato sepolto nel giardino della villa di Quebert, proprio accanto al manoscritto del suo capolavoro. Per salvare il suo amico dalla pena di morte, Marcus dovrà immergersi in un\'indagine in cui ogni verità ne nasconde un\'altra, scoprendo che il passato non muore mai davvero.\"', '/covers/laveritasulcasoharryquebert.jpg', 'ansioso'),
(22, 'L\'Enigma della camera 622', 'Joel Dicker', '\"La vita è un romanzo di cui si conosce già la fine: alla fine si muore. L\'unica cosa che conta non è come finisce, ma come riempiamo le pagine.\"', '\"Una notte di dicembre, un omicidio irrisolto scuote il lussuoso Palace de Verbier sulle Alpi svizzere. Anni dopo, lo stesso Joël Dicker soggiorna nell\'hotel per riprendersi da una delusione amorosa, ma nota un dettaglio inquietante: la camera 622 non esiste più nel numero delle stanze. Spinto dalla curiosità e aiutato da un\'affascinante aspirante scrittrice, inizia a indagare sul passato, scoperchiando un intreccio di segreti bancari, triangoli amorosi e giochi di potere in cui nessuno è davvero chi dice di essere.\"', '/covers/lenigmadellacamera622.jpg', 'ansioso'),
(23, 'L\'Alchimista', 'Paulo Coelho', '\"Quando desideri una cosa, tutto l\'Universo trama affinché tu possa realizzarla.\"', '\"Santiago, un giovane pastore andaluso, intraprende un viaggio avventuroso dalle sue terre natie fino al deserto egiziano, alla ricerca di un tesoro sognato ai piedi delle Piramidi. Lungo il cammino incontrerà una zingara, un re e un misterioso alchimista che lo guideranno verso la scoperta più grande: il vero tesoro non è l\'oro materiale, ma la capacità di ascoltare il proprio cuore e il coraggio di realizzare la propria Leggenda Personale.\"', '/covers/lalchimista.jpg', 'felice'),
(24, 'Finchè il caffè è caldo', 'Toshikazu Kawaguchi', '\"Anche se non si può cambiare il presente tornando nel passato, si può tornare nel presente con un cuore diverso.\"', '\"In un piccolo vicolo di Tokyo esiste una caffetteria leggendaria che offre ai suoi clienti un\'esperienza unica: la possibilità di viaggiare nel tempo. Ma le regole sono rigide e strane: non ci si può alzare dalla sedia, il presente non cambierà qualunque cosa accada e, soprattutto, bisogna tornare indietro prima che il caffè si raffreddi. Quattro storie di persone che vogliono rivedere qualcuno per l\'ultima volta, scoprendo che, anche se non si può cambiare la realtà, si può sempre cambiare il proprio cuore.\"', '/covers/fincheilcaffeecaldo.jpg', 'felice'),
(25, 'I miei giorni alla libreria Morisaki', 'Satoshi Yagisawa', '\"Non importa quanto il mondo possa essere crudele o quanto ti senta sola, i libri ti accoglieranno sempre. Sono lì per te, pronti a offrirti un rifugio sicuro.\"', '\"Takako, venticinquenne col cuore spezzato e senza più un lavoro, accetta con riluttanza di trasferirsi nella stanza sopra la vecchia libreria dell\'eccentrico zio Satoru, nel quartiere di Jimbocho, il paradiso dei lettori a Tokyo. Circondata da migliaia di volumi usati, inizialmente si sente persa, ma lentamente scoprirà che le storie hanno il potere di curare le ferite dell\'anima e che la vita può ricominciare proprio dove meno te lo aspetti.\"', '/covers/imieigiorniallalibreriamorisaki.jpg', 'felice'),
(26, 'Il Piccolo Principe', 'Antoine de Saint-Exupéry', '\"Non si vede bene che col cuore. L\'essenziale è invisibile agli occhi.\"', '\"Un pilota precipita con il suo aereo nel deserto del Sahara e incontra un bambino biondo venuto da un lontano asteroide. Attraverso il racconto dei suoi viaggi su pianeti abitati da strani personaggi adulti, il Piccolo Principe offre una profonda meditazione sull\'amicizia, l\'amore, la perdita e su come gli adulti dimentichino spesso di essere stati bambini. Una fiaba filosofica che insegna a guardare oltre le apparenze.\"', '/covers/ilpiccoloprincipe.jpg', 'felice'),
(27, 'La mia famiglia e altri animali', 'Gerald Durrell', '\"La graduale magia dell\'isola ci avvolgeva delicatamente come polline.\"', '\"Il racconto autobiografico esilarante e solare dell\'infanzia dell\'autore sull\'isola greca di Corfù negli anni Trenta. Tra una madre ansiosa, fratelli eccentrici (tra cui lo scrittore Larry) e una sfilata infinita di animali selvatici che il piccolo Gerald porta in casa — dai gufi alle tartarughe, dagli scorpioni alle gazze — è un inno alla libertà, alla scoperta della natura e al calore di una famiglia felicemente disfunzionale.\"', '/covers/lamiafamigliaealtrianimali.jpg', 'felice'),
(28, 'Il barone rampante', 'Italo Calvino', '\"Chi vuole guardare bene la terra deve tenersi alla distanza necessaria.\"', '\"Dopo un litigio con i genitori per un piatto di lumache rifiutato, il dodicenne Cosimo Piovasco di Rondò sale su un elce del giardino e promette di non scendere mai più. Manterrà la promessa per tutta la vita, spostandosi solo da un ramo all\'altro. Da lassù, costruisce un mondo tutto suo, studia, caccia, si innamora e partecipa persino ai grandi eventi della storia, offrendoci una prospettiva unica: quella di chi guarda il mondo con il distacco necessario per comprenderlo davvero.\"', '/covers/ilbaronerampante.jpg', 'felice'),
(29, 'Se i gatti scomparissero dal mondo', 'Genki Kawamura', '\"Se i gatti scomparissero dal mondo, come cambierebbe la mia vita? E come cambierebbe la vita del mondo?\"', '\"Un giovane postino scopre di avere pochi giorni di vita a causa di una malattia terminale. Il Diavolo gli appare con una proposta bizzarra: potrà guadagnare un giorno di vita in più per ogni cosa che accetterà di far sparire per sempre dal mondo. Scompaiono i telefoni, i film, gli orologi... ma quando toccherà ai gatti (e al suo amato gatto Cavolo), il protagonista dovrà decidere cosa rende la vita degna di essere vissuta.\"', '/covers/seigattiscomparisserodalmondo.jpg', 'triste'),
(30, 'Norwegian Wood', 'Haruki Murakami', '\"La morte non è l\'opposto della vita, ma una sua parte intrinseca.\"', '\"Sulle note della canzone dei Beatles che dà il titolo al libro, Toru Watanabe ricorda la sua giovinezza nella Tokyo degli anni Sessanta. È un racconto struggente segnato dal suicidio del suo migliore amico Kizuki e dall\'amore complicato per la fragile Naoko, la ragazza che Kizuki ha lasciato dietro di sé. Tra dolore, solitudine e l\'incontro con la vivace Midori, Toru dovrà imparare che crescere significa accettare la perdita come parte integrante della vita.\"', '/covers/norwegianwood.jpg', 'triste'),
(31, 'Una vita come tante', 'Hanya Yanagihara', '\"Le cose si rompono, e a volte si riparano, e nella maggior parte dei casi ti rendi conto che non importa ciò che viene distrutto, la vita riprende.\"', '\"La storia monumentale e straziante di un\'amicizia lunga decenni tra quattro compagni di college che si trasferiscono a New York: l\'attore Willem, l\'artista JB, l\'architetto Malcolm e l\'enigmatico avvocato Jude St. Francis. Col passare degli anni, le loro vite si cementano attorno a Jude, un uomo brillante ma spezzato, tormentato da traumi infantili indicibili e da un dolore fisico e psicologico che sembra non avere fine. Un\'esplorazione brutale e commovente dei limiti della sopportazione umana e del potere salvifico dell\'amore fraterno.\"', '/covers/unavitacometante.jpg', 'triste'),
(32, 'Le otto montagne', 'Paolo Cognetti', '\"Non importa quanto vai in alto, non c\'è niente lassù. Il passato è a valle.\"', '\"Pietro è un ragazzo di città, solitario e un po\' scontroso; Bruno è l\'ultimo bambino rimasto in un villaggio di montagna dimenticato. La loro amicizia nasce in silenzio tra i sentieri delle Alpi e resiste al passare dei decenni, alle distanze e alle scelte di vita opposte. Mentre Pietro gira il mondo cercando se stesso, Bruno resta ancorato alla sua terra. Una storia potente su cosa significa diventare uomini, sull\'eredità dei padri e sulla montagna come rifugio e destino.\"', '/covers/leottomontagne.jpg', 'triste'),
(33, 'Un giorno questo dolore ti sarà utile', 'Peter Cameron', '\"Il difficile è non lasciarsi abbattere dai momenti brutti. Devi considerarli un dono – un dono crudele, ma pur sempre un dono.\"', '\"James Sveck è un diciottenne newyorkese solitario e anticonformista che si sente profondamente estraneo al mondo che lo circonda. Mentre i suoi coetanei si preparano per il college, lui sogna di comprare una vecchia casa nel Midwest per vivere in isolamento totale e leggere tutto il giorno. Lavorando nella galleria d\'arte della madre e frequentando malvolentieri una psicologa, James cerca di trovare il suo posto in una realtà che gli sembra assurda e priva di senso, affrontando con ironia e malinconia il difficile passaggio all\'età adulta.\"', '/covers/ungiornoquestodolore.jpg', 'triste'),
(34, 'Le notti bianche', 'Fëdor Dostoevskij', '\"Dio mio! Un intero attimo di beatitudine! È forse poco, sia pure per tutta la vita di un uomo?\"', '\"Nella magica atmosfera di una San Pietroburgo dove il sole sembra non tramontare mai, un sognatore solitario incontra Nasten\'ka, una giovane donna in lacrime su un ponte. Nel corso di quattro notti illuminate da una luce irreale, i due sconosciuti si aprono l\'un l\'altro, intrecciando le loro solitudini e le loro speranze. Un racconto delicato e struggente sull\'amore non corrisposto e sulla fugacità della felicità.\"', '/covers/lenottibianche.jpg', 'triste'),
(35, 'Il Buio oltre la siepe', 'Harper Lee', '\"Non riesci mai a capire una persona se non consideri le cose dal suo punto di vista... finché non ti arrampichi dentro la sua pelle e non ci vai a spasso.\"', '\"Nell\'Alabama razzista degli anni \'30, l\'avvocato Atticus Finch accetta l\'incarico impossibile di difendere Tom Robinson, un bracciante nero ingiustamente accusato di violenza su una ragazza bianca. Attraverso gli occhi innocenti della figlia Scout, il romanzo smaschera la brutalità del pregiudizio e celebra l\'eroismo silenzioso di chi sceglie di fare la cosa giusta, anche quando sa di aver perso in partenza.\"', '/covers/ilbuiooltrelasiepe.jpg', 'arrabbiato'),
(36, 'Fight Club', 'Chuck Palahniuk', '\"Le cose che possiedi alla fine ti possiedono. Solo dopo aver perso tutto, siamo liberi di fare qualsiasi cosa.\"', '\"Un impiegato anonimo e insonne, disgustato dalla sua vita vuota fatta solo di cataloghi IKEA e cultura aziendale, trova un\'improbabile via di fuga nell\'incontro con il carismatico Tyler Durden. Insieme fondano il Fight Club, un luogo segreto dove uomini comuni si picchiano a sangue per sentirsi di nuovo vivi. Ma quello che inizia come uno sfogo violento si trasforma presto nel Progetto Mayhem, un piano anarchico e terrificante per distruggere la civiltà moderna.\"', '/covers/fightclub.jpg', 'arrabbiato'),
(37, '1984', 'George Orwell', '\"Libertà è la libertà di dire che due più due fa quattro. Se è concesso questo, tutto il resto segue.\"', '\"In un futuro totalitario agghiacciante, il Partito controlla ogni aspetto della vita umana sotto l\'occhio onnipresente del Grande Fratello. Winston Smith, un funzionario incaricato di riscrivere la storia per adattarla alla propaganda, commette il crimine supremo: pensare liberamente. Il suo tentativo di ribellione disperata per preservare la propria umanità, la memoria e l\'amore si scontra con una macchina di repressione perfetta che non vuole solo l\'obbedienza, ma il controllo totale della mente.\"', '/covers/1984.jpg', 'arrabbiato'),
(38, 'Il conte di Montecristo', 'Alexandre Dumas', '\"Tutta l\'umana saggezza è racchiusa in queste due parole: aspettare e sperare.\"', '\"Edmond Dantès, giovane marinaio con una vita perfetta davanti a sé, viene tradito da amici invidiosi nel giorno delle sue nozze e gettato in una prigione segreta per quattordici anni. Nel buio della cella, la disperazione si trasforma in una fredda determinazione. Dopo una fuga rocambolesca e il ritrovamento di un tesoro immenso, Edmond torna sotto le spoglie del misterioso Conte di Montecristo per attuare una vendetta lenta, teatrale e spietata contro coloro che gli hanno rubato la vita.\"', '/covers/ilcontedimontecristo.jpg', 'arrabbiato'),
(39, 'La fattoria degli animali', 'George Orwell', '\"Tutti gli animali sono uguali, ma alcuni sono più uguali degli altri.\"', '\"Gli animali della Fattoria Padronale, stanchi dei maltrattamenti, si ribellano e cacciano il proprietario umano per fondare una società basata sull\'uguaglianza e la giustizia. Ma quello che inizia come un sogno utopico viene lentamente corrotto dall\'interno: i maiali, guidati dall\'astuto Napoleon, prendono il potere e instaurano una dittatura ancora più brutale di quella precedente, riscrivendo le leggi a loro vantaggio fino a diventare indistinguibili dagli uomini.\"', '/covers/lafattoriadeglianimali.jpg', 'arrabbiato'),
(40, 'Arancia meccanica', 'Anthony Burgess', '\"È un peccato volere il male? O è solo un modo di affermare se stessi? Perché se l\'uomo non può scegliere, cessa di essere uomo.\"', '\"In un futuro violento e grottesco, il giovane Alex è il capo dei \'drughi\', una banda che si diverte a compiere atti di \'ultra-violenza\' gratuita. Dopo essere stato tradito e arrestato, Alex accetta di sottoporsi alla sperimentale \'Cura Ludovico\' per ottenere la libertà anticipata. Il trattamento lo condiziona a provare un dolore fisico insopportabile al solo pensiero della violenza, rendendolo \'buono\' a forza. Ma un uomo che non può scegliere tra il bene e il male è ancora un uomo o è solo un\'arancia meccanica caricata a molla?\"', '/covers/aranciameccanica.jpg', 'arrabbiato'),
(41, 'Guida galattica per gli autostoppisti', 'Douglas Adams', 'La regola d\'oro della Guida (e della vita):\r\n\r\n\"Niente panico.\"', '\"Arthur Dent viene salvato dalla distruzione della Terra dal suo amico alieno Ford. Armati solo di un asciugamano, iniziano un viaggio assurdo attraverso l\'universo seguendo i consigli di un libro che riporta in copertina la scritta: NIENTE PANICO.\"', '/covers/guidagalatticapergliautostoppisti.jpg', 'annoiato'),
(42, 'Il codice da Vinci', 'Dan Brown', '\"La mente vede ciò che sceglie di vedere.\"', '\"Robert Langdon indaga su un misterioso omicidio al Louvre. Seguendo una scia di codici nascosti nei capolavori di Leonardo, scopre un segreto antico e sconvolgente che potrebbe riscrivere la storia dell\'umanità.\"', '/covers/codicedavinci.jpg', 'annoiato'),
(43, 'L\'ombra del vento', 'Carlos Ruiz Zafón', '\"Ogni libro possiede un\'anima, l\'anima di chi lo ha scritto e l\'anima di coloro che lo hanno letto, vissuto e sognato.\"', '\"Nella nebbiosa Barcellona del 1945, il giovane Daniel viene condotto al segreto Cimitero dei Libri Dimenticati. Qui sceglie un volume \'maledetto\' che cambierà il suo destino, trascinandolo in un labirinto di amori tragici e oscuri segreti del passato.\"', '/covers/lombradelvento.jpg', 'annoiato'),
(44, 'Lo Hobbit', 'J.R.R. Tolkien', '\"In un buco nel terreno viveva uno hobbit.\"', '\"Bilbo Baggins, un tranquillo hobbit amante della comodità, viene trascinato dal mago Gandalf e da tredici nani in un\'avventura epica attraverso le Terre Selvagge per riconquistare un tesoro rubato dal temibile drago Smaug.\"', '/covers/lohobbit.jpg', 'annoiato'),
(45, 'Dune', 'Frank Herbert', '\"Non devo avere paura. La paura uccide la mente. La paura è la piccola morte che porta alla distruzione totale.\"', '\"Sul pianeta desertico Arrakis, unica fonte della preziosa spezia che permette i viaggi interstellari, il giovane Paul Atreides deve sopravvivere a tradimenti politici e mostri di sabbia per compiere il suo destino e guidare la ribellione dei Fremen.\"\r\n\r\n', '/covers/dune.jpg', 'annoiato'),
(46, 'Ready Player One', 'Ernest Cline', '\"Nessuno è mai pronto per niente, ma è proprio questo il bello.\"', '\"Nel 2045 il mondo reale è al collasso e l\'umanità si rifugia in OASIS, un universo virtuale utopico. Il giovane Wade Watts dedica la sua vita a decifrare gli enigmi pop anni \'80 lasciati dal creatore per trovarne l\'eredità miliardaria.\"', '/covers/readyplayerone.jpg', 'annoiato'),
(47, 'Tre uomini in barca', 'Jerome K. Jerome', '\"Mi piace il lavoro, mi affascina completamente; potrei starmene seduto per ore e ore a guardarlo.\"', '\"Tre amici ipocondriaci e il loro cane Montmorency decidono di fare una gita in barca sul Tamigi per curare i loro mali immaginari. Ne nasce una serie di disavventure comiche e situazioni assurde che trasformano il viaggio in un\'odissea esilarante.\"', '/covers/treuominiinbarca.jpg', 'divertito'),
(48, 'Il diario di Bridget Jones', 'Helen Fielding', '\"È una verità universalmente riconosciuta che quando una parte della tua vita comincia ad andare bene, quell\'altra cade a pezzi.\"', '\"Le confessioni esilaranti di una trentenne single alle prese con la bilancia, le sigarette, l\'alcol e gli uomini sbagliati. Un diario ironico e disastroso sulla ricerca dell\'amore e dell\'equilibrio interiore.\"', '/covers/ildiariodibridgetjones.jpg', 'divertito'),
(49, 'Marcovaldo', 'Italo Calvino', '\"Aveva questo Marcovaldo un occhio poco adatto alla vita di città: cartelli, semafori, vetrine... mai fermavano il suo sguardo.\"', '\"Un manovale ingenuo e sognatore cerca ostinatamente la natura nel grigio cemento di una città industriale. Tra funghi velenosi, piccioni e gatti, le sue avventure tragicomiche raccontano con ironia il difficile rapporto tra l\'uomo moderno e l\'ambiente urbano.\"', '/covers/marcovaldo.jpg', 'divertito'),
(50, 'Cent\'anni di solitudine', 'G.G. Márquez', '\"Molti anni dopo, di fronte al plotone di esecuzione, il colonnello Aureliano Buendía si sarebbe ricordato di quel remoto pomeriggio in cui suo padre lo aveva condotto a conoscere il ghiaccio.\"', '\"La saga epica e onirica della famiglia Buendía nell\'immaginaria città di Macondo. Attraverso sette generazioni, tra guerre, amori proibiti e piogge di fiori gialli, i protagonisti vivono un destino ineluttabile segnato da una solitudine che non lascia scampo.\"', '/covers/centannidisolitudine.jpg', 'divertito'),
(51, 'Don Chisciotte', 'Miguel de Cervantes', '\"La libertà, Sancho, è uno dei doni più preziosi che i cieli abbiano concesso agli uomini.\"', '\"Un nobiluomo di campagna perde il senno a forza di leggere romanzi cavallereschi e decide di farsi cavaliere errante. Insieme al fedele e pragmatico scudiero Sancho Panza, vaga per la Spagna combattendo contro mulini a vento scambiati per giganti, in un\'avventura che è al tempo stesso esilarante e commovente.\"', '/covers/donchisciottedellamancha', 'divertito'),
(52, 'Il gabbiano Jonathan Livingston', 'Richard Bach', '\"Hai la libertà di essere te stesso, il tuo vero te stesso, qui e ora, e niente te lo può impedire.\"', '\"Jonathan è un gabbiano diverso dagli altri: non vola solo per procurarsi il cibo, ma per la gioia pura della velocità e della perfezione. Emarginato dal suo stormo, intraprende un viaggio spirituale per scoprire che non esistono limiti se non quelli che ci imponiamo da soli.\"', '/covers/ilgabbianojonathanlivingston.jpg', 'divertito'),
(53, 'I dolori del giovane Werther', 'J.W. Goethe', '\"La natura umana ha i suoi limiti: può sopportare la gioia, il dolore, le pene fino a un certo grado; se questo si supera, soccombe.\"', '\"Attraverso lettere appassionate all\'amico Wilhelm, il giovane Werther racconta il suo amore assoluto e impossibile per Lotte, già promessa a un altro uomo. Un viaggio nell\'animo umano che esplora come un sentimento troppo grande possa consumare la vita stessa.\"', '/covers/idoloridelgiovanewerther.jpg', 'divertito'),
(54, 'Il Piccolo Principe', 'Antoine de Saint-Exupéry', 'Non si vede bene che col cuore. L\'essenziale è invisibile agli occhi.', 'Un pilota precipita nel Sahara e incontra un bambino biondo venuto da un asteroide. Una fiaba filosofica eterna sull\'amicizia, l\'amore e il senso della vita.', '/covers/ilpiccoloprincipe.jpg', 'felice'),
(55, 'La mia famiglia e altri animali', 'Gerald Durrell', 'La graduale magia dell\'isola ci avvolgeva delicatamente come polline.', 'Il racconto esilarante e solare dell\'infanzia dell\'autore sull\'isola greca di Corfù, tra eccentrici familiari e una fauna stravagante.', '/covers/lamiafamigliaealtrianimali.jpg', 'felice'),
(56, 'Il barone rampante', 'Italo Calvino', 'Chi vuole guardare bene la terra deve tenersi alla distanza necessaria.', 'Il giovane Cosimo decide di salire sugli alberi per non scenderne mai più, vivendo una vita piena di avventure e libertà guardando il mondo dall\'alto.', '/covers/ilbaronerampante.jpg', 'felice'),
(57, 'Se i gatti scomparissero dal mondo', 'Genki Kawamura', 'Se i gatti scomparissero dal mondo, come cambierebbe la mia vita? E come cambierebbe la vita del mondo?', 'Un postino scopre di avere i giorni contati e fa un patto col diavolo: un giorno di vita in più per ogni cosa che farà sparire dal mondo. Ma cosa siamo disposti a perdere per sopravvivere?', '/covers/seigattiscomparissero.jpg', 'triste'),
(58, 'Norwegian Wood', 'Haruki Murakami', 'La morte non è l\'opposto della vita, ma una sua parte intrinseca.', 'Toru Watanabe ricorda i suoi anni universitari nella Tokyo degli anni Sessanta, segnati dall\'amore per la fragile e misteriosa Naoko e dalla tragica morte del loro migliore amico.', '/covers/norwegianwood.jpg', 'triste'),
(59, 'Una vita come tante', 'Hanya Yanagihara', 'Le cose si rompono, e a volte si riparano, e nella maggior parte dei casi ti rendi conto che non importa ciò che viene distrutto, la vita riprende.', 'La struggente e dolorosa storia di un\'amicizia lunga una vita tra quattro ragazzi a New York, e del passato terribile e indicibile che tormenta uno di loro, Jude.', '/covers/unavitacometante.jpg', 'triste'),
(60, 'Le otto montagne', 'Paolo Cognetti', 'Non importa quanto vai in alto, non c\'è niente lassù. Il passato è a valle.', 'Pietro è un ragazzo di città, Bruno un pastore. La loro amicizia nasce sulle cime delle Alpi e resiste al tempo e alla distanza, diventando un rifugio per le loro anime solitarie.', '/covers/leottomontagne.jpg', 'triste'),
(61, 'Un giorno questo dolore ti sarà utile', 'Peter Cameron', 'Non voglio che succeda niente. Voglio solo starmene tranquillo.', 'James Sveck, diciottenne newyorkese solitario e incompreso, cerca di trovare il suo posto nel mondo evitando il college e la vita borghese che tutti si aspettano da lui.', '/covers/ungiornoquesto.jpg', 'triste'),
(62, 'Le notti bianche', 'Fëdor Dostoevskij', 'Dio mio! Un intero attimo di beatitudine! È forse poco, sia pure per tutta la vita di un uomo?', 'Un sognatore solitario vaga nella Pietroburgo notturna e incontra Nasten\'ka. Per quattro notti vivranno un amore fatto solo di confidenze e speranze, destinato a svanire all\'alba.', '/covers/lenottibianche.jpg', 'triste'),
(63, 'Se i gatti scomparissero dal mondo', 'Genki Kawamura', 'Se i gatti scomparissero dal mondo, come cambierebbe la mia vita? E come cambierebbe la vita del mondo?', 'Un postino scopre di avere i giorni contati e fa un patto col diavolo: un giorno di vita in più per ogni cosa che farà sparire dal mondo. Un racconto delicato su cosa rende la vita degna di essere vissuta.', '/covers/seigattiscomparissero.jpg', 'triste'),
(64, 'Norwegian Wood', 'Haruki Murakami', 'La morte non è l\'opposto della vita, ma una sua parte intrinseca.', 'Toru ricorda i suoi anni universitari nella Tokyo degli anni Sessanta, segnati dall\'amore per la fragile Naoko e dalla tragica morte del loro migliore amico. Un romanzo cult sulla perdita e sulla crescita.', '/covers/norwegianwood.jpg', 'triste'),
(65, 'Una vita come tante', 'Hanya Yanagihara', 'Le cose si rompono, e a volte si riparano, e nella maggior parte dei casi ti rendi conto che non importa ciò che viene distrutto, la vita riprende.', 'La struggente storia di un\'amicizia lunga una vita tra quattro ragazzi a New York, e del passato terribile che tormenta uno di loro, Jude. Un libro doloroso e indimenticabile sull\'amore e la sofferenza.', '/covers/unavitacometante.jpg', 'triste'),
(66, 'Le otto montagne', 'Paolo Cognetti', 'Non importa quanto vai in alto, non c\'è niente lassù. Il passato è a valle.', 'Pietro è un ragazzo di città, Bruno un pastore. La loro amicizia nasce sulle cime delle Alpi e resiste al tempo e alla distanza, diventando un rifugio per le loro anime solitarie.', '/covers/leottomontagne.jpg', 'triste'),
(67, 'Un giorno questo dolore ti sarà utile', 'Peter Cameron', 'Non voglio che succeda niente. Voglio solo starmene tranquillo.', 'James Sveck, diciottenne newyorkese solitario e incompreso, cerca di trovare il suo posto nel mondo evitando il college e la vita borghese che tutti si aspettano da lui.', '/covers/ungiornoquesto.jpg', 'triste'),
(68, 'Le notti bianche', 'Fëdor Dostoevskij', 'Dio mio! Un intero attimo di beatitudine! È forse poco, sia pure per tutta la vita di un uomo?', 'Un sognatore solitario vaga nella Pietroburgo notturna e incontra Nasten\'ka. Per quattro notti vivranno un amore fatto solo di confidenze e speranze, destinato a svanire all\'alba.', '/covers/lenottibianche.jpg', 'triste'),
(69, 'I dolori del giovane Werther', 'J.W. Goethe', 'E in questo non sono tutti uguali gli uomini? La razza umana è una cosa monotona.', 'Attraverso le sue lettere, il giovane Werther racconta la sua passione assoluta e impossibile per Lotte, promessa sposa a un altro. Il romanzo che ha definito il romanticismo e il dolore dell\'amore.', '/covers/werther.jpg', 'triste'),
(70, 'Il Buio oltre la siepe', 'Harper Lee', 'Non riesci mai a capire una persona se non consideri le cose dal suo punto di vista... se non ti metti nella sua pelle e non ci vai a spasso.', 'Nell\'Alabama razzista degli anni Trenta, l\'avvocato Atticus Finch difende un uomo nero ingiustamente accusato. Una storia potente sull\'indignazione contro il pregiudizio.', '/covers/ilbuiooltrelasiepe.jpg', 'arrabbiato'),
(71, 'Fight Club', 'Chuck Palahniuk', 'Le cose che possiedi alla fine ti possiedono.', 'Un impiegato insonne trova sfogo in un club segreto di combattimento che diventa presto un progetto anarchico per distruggere la civiltà moderna.', '/covers/fightclub.jpg', 'arrabbiato'),
(72, '1984', 'George Orwell', 'La libertà è la libertà di dire che due più due fa quattro. Se questo è concesso, tutto il resto segue.', 'In un futuro da incubo dove il Grande Fratello controlla ogni pensiero, Winston Smith tenta una disperata ribellione per conservare la propria umanità.', '/covers/1984.jpg', 'arrabbiato'),
(73, 'Il conte di Montecristo', 'Alexandre Dumas', 'Tutta l\'umana saggezza è racchiusa in queste due parole: aspettare e sperare.', 'Edmond Dantès, ingiustamente imprigionato per 14 anni nel castello d\'If, evade e dedica la sua vita a una vendetta implacabile contro chi gli ha rubato la felicità.', '/covers/montecristo.jpg', 'arrabbiato'),
(74, 'La fattoria degli animali', 'George Orwell', 'Tutti gli animali sono uguali, ma alcuni sono più uguali degli altri.', 'Gli animali si ribellano ai padroni umani per creare una società uguale, ma i maiali prendono il potere instaurando una dittatura ancora più crudele.', '/covers/fattoriadeglianimali.jpg', 'arrabbiato'),
(75, 'Arancia meccanica', 'Anthony Burgess', 'È un peccato volere il male? O è solo un modo di affermare se stessi?', 'Il leader di una banda criminale viene sottoposto a una cura sperimentale per eliminare la violenza, privandolo però del libero arbitrio.', '/covers/aranciameccanica.jpg', 'arrabbiato'),
(76, 'Guida galattica per gli autostoppisti', 'Douglas Adams', 'Niente panico.', 'Arthur Dent scampa alla fine del mondo e inizia un viaggio assurdo e spassoso nell\'universo con la sua guida e un asciugamano.', '/covers/guidagalattica.jpg', 'annoiato'),
(77, 'Il codice da Vinci', 'Dan Brown', 'La mente vede ciò che vuole vedere.', 'Un omicidio al Louvre svela un\'antica cospirazione religiosa nascosta nelle opere d\'arte che potrebbe scuotere le fondamenta del Cristianesimo.', '/covers/codicedavinci.jpg', 'annoiato'),
(78, 'L\'ombra del vento', 'Carlos Ruiz Zafón', 'Ogni libro possiede un\'anima, l\'anima di chi lo ha scritto e l\'anima di coloro che lo hanno letto.', 'Nella Barcellona del 1945, il giovane Daniel viene condotto al Cimitero dei Libri Dimenticati e sceglie un libro maledetto che cambierà la sua vita.', '/covers/ombradelvento.jpg', 'annoiato'),
(79, 'Lo Hobbit', 'J.R.R. Tolkien', 'In un buco nel terreno viveva uno hobbit.', 'Bilbo Baggins, un tranquillo hobbit, viene trascinato da un mago e tredici nani in un\'avventura epica per riconquistare un tesoro custodito da un drago.', '/covers/lohobbit.jpg', 'annoiato'),
(80, 'Dune', 'Frank Herbert', 'Non devo avere paura. La paura uccide la mente.', 'Sul pianeta deserto Arrakis, il giovane Paul Atreides deve affrontare tradimenti politici e mostri di sabbia per compiere il suo destino.', '/covers/dune.jpg', 'annoiato'),
(81, 'Ready Player One', 'Ernest Cline', 'La realtà è l\'unica cosa che è reale.', 'In un futuro distopico, l\'umanità si rifugia nel mondo virtuale di OASIS. Wade Watts partecipa a una caccia al tesoro digitale per ereditarne il controllo.', '/covers/readyplayerone.jpg', 'annoiato'),
(82, 'Tre uomini in barca', 'Jerome K. Jerome', 'Mi piace il lavoro, mi affascina completamente; potrei starmene seduto per ore e ore a guardarlo.', 'Tre amici ipocondriaci (e un cane fox terrier) decidono di fare una gita in barca sul Tamigi per rilassarsi, ma finiscono in una serie di disavventure comiche ed esilaranti.', '/covers/treuominiinbarca.jpg', 'divertito'),
(83, 'Il diario di Bridget Jones', 'Helen Fielding', 'È una verità universalmente riconosciuta che quando una parte della tua vita comincia ad andare bene, quell\'altra cade a pezzi.', 'Le confessioni oneste e tragicomiche di una trentenne londinese single, alle prese con la bilancia, le sigarette, il lavoro e la ricerca disperata dell\'uomo giusto.', '/covers/bridgetjones.jpg', 'divertito'),
(84, 'Marcovaldo', 'Italo Calvino', 'Aveva questo di buono, Marcovaldo: che riusciva a scoprire la natura anche dove di natura non ce n\'era quasi più.', 'Le avventure agrodolci di un manovale ingenuo che cerca ostinatamente la natura in una grigia città industriale, finendo spesso in situazioni assurde e divertenti.', '/covers/marcovaldo.jpg', 'divertito'),
(85, 'Cent\'anni di solitudine', 'G.G. Márquez', 'La stirpe condannata a cent\'anni di solitudine non aveva una seconda opportunità sulla terra.', 'La saga epica, magica e stravagante della famiglia Buendía nel villaggio di Macondo, tra piogge di fiori, fantasmi, pesciolini d\'oro e amori impossibili.', '/covers/centannisolidutine.jpg', 'divertito'),
(86, 'Don Chisciotte', 'Miguel de Cervantes', 'La libertà, Sancio, è uno dei doni più preziosi che i cieli abbiano concesso agli uomini.', 'Un nobile spagnolo perde la testa leggendo troppi romanzi cavallereschi e parte all\'avventura col suo scudiero Sancio Panza, combattendo contro mulini a vento che crede giganti.', '/covers/donchisciotte.jpg', 'divertito'),
(87, 'Il gabbiano Jonathan Livingston', 'Richard Bach', 'Più in alto vola il gabbiano, e più vede lontano.', 'La favola di un gabbiano anticonformista che si rifiuta di volare solo per cercare cibo, dedicando la sua vita alla ricerca della perfezione e della velocità.', '/covers/gabbianojonathan.jpg', 'divertito');

-- --------------------------------------------------------

CREATE TABLE `reviews` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `book_title` varchar(100) NOT NULL,
  `mood` varchar(50) NOT NULL,
  `rating` int(11) NOT NULL,
  `comment` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


INSERT INTO `reviews` (`id`, `username`, `book_title`, `mood`, `rating`, `comment`, `created_at`) VALUES
(1, 'LettoreSensibile', 'Una vita come tante', 'Triste', 5, 'Un pugno nello stomaco. Una storia dolorosa ma scritta divinamente.', '2026-01-28 10:17:40'),
(2, 'Melanconia_Blue', 'Non lasciarmi', 'Triste', 4, 'Un senso di malinconia che ti resta addosso per giorni. Bellissimo.', '2026-01-28 10:17:40'),
(3, 'Sognatrice88', 'Il castello errante di Howl', 'Felice', 5, 'Pura magia. Mi ha fatto tornare bambina e sorridere tutto il tempo.', '2026-01-28 10:17:40'),
(4, 'AustenFan', 'Orgoglio e Pregiudizio', 'Felice', 5, 'Il lieto fine per eccellenza. Rileggerlo mi mette sempre di buonumore.', '2026-01-28 10:17:40'),
(5, 'GialloAddict', 'Dieci piccoli indiani', 'Ansioso', 5, 'Tensione alle stelle! Non riuscivo a smettere di girare le pagine.', '2026-01-28 10:17:40'),
(6, 'KingLover', 'Misery', 'Ansioso', 5, 'Claustrofobico. Ho avuto l\'ansia per il protagonista dall\'inizio alla fine.', '2026-01-28 10:17:40'),
(7, 'Ribelle_X', '1984', 'Arrabbiato', 5, 'Fa rabbia vedere come le dinamiche di potere descritte siano ancora attuali.', '2026-01-28 10:17:40'),
(8, 'GeorgeO', 'La fattoria degli animali', 'Arrabbiato', 4, 'Il finale ti lascia con un senso di ingiustizia che fa davvero infuriare.', '2026-01-28 10:17:40'),
(9, 'RidiCheTiPassa', 'Tre uomini in barca', 'Divertito', 3, 'Alcune scene sono esilaranti, specialmente quella del formaggio!', '2026-01-28 10:17:40'),
(10, 'MarvinTheRobot', 'Guida galattica per gli autostoppisti', 'Divertito', 5, 'Assurdo e geniale. \"Addio e grazie per tutto il pesce!\" mi fa sempre ridere.', '2026-01-28 10:17:40'),
(11, 'Anonimo', '1984', 'Arrabbiato', 5, 'davvero crudo ma bello come libro ', '2026-01-28 10:25:32');

-- --------------------------------------------------------

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `nome` varchar(50) DEFAULT NULL,
  `cognome` varchar(50) DEFAULT NULL,
  `birthdate` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` (`id`, `username`, `email`, `password`, `created_at`, `nome`, `cognome`, `birthdate`) VALUES
(1, 'laurascotti', 'laura@moodread.com', 'admin123', '2026-01-28 09:10:49', NULL, NULL, NULL),
(2, 'anadiarciuc', 'ana@moodread.com', 'admin123', '2026-01-28 09:10:49', NULL, NULL, NULL),
(3, 'marco_rossi', 'marco.rossi@email.it', 'password123', '2026-01-28 09:10:49', NULL, NULL, NULL),
(4, 'sofiabianchi', 'sofia.b99@gmail.com', 'leggere2024', '2026-01-28 09:10:49', NULL, NULL, NULL),
(5, 'alessandro_m90', 'ale.magno@libero.it', 'roma1990', '2026-01-28 09:10:49', NULL, NULL, NULL),
(6, 'giuliaverdi', 'giulia.verdi@outlook.com', 'girasole88', '2026-01-28 09:10:49', NULL, NULL, NULL),
(7, 'DavideEspo', 'davide.esposito@live.com', 'napoli10', '2026-01-28 09:10:49', NULL, NULL, NULL),
(8, 'LibroCuore', 'cuore.libri@test.com', 'romanzoRosa', '2026-01-28 09:10:49', NULL, NULL, NULL),
(9, 'IlLettoreNotturno', 'night.reader@test.com', 'insonnia', '2026-01-28 09:10:49', NULL, NULL, NULL),
(10, 'GiallistaPerCaso', 'thriller.fan@test.com', 'sherlock', '2026-01-28 09:10:49', NULL, NULL, NULL),
(11, 'Pagina77', 'pagina77@email.it', 'segnalibro', '2026-01-28 09:10:49', NULL, NULL, NULL),
(12, 'BookWorm_It', 'verme.solitario@gmail.com', 'biblioteca', '2026-01-28 09:10:49', NULL, NULL, NULL),
(13, 'Francesca_N', 'francy.neri@email.it', 'mareblu', '2026-01-28 09:10:49', NULL, NULL, NULL),
(14, 'Lorenzo95', 'lorenzo1995@hotmail.com', 'calcio5', '2026-01-28 09:10:49', NULL, NULL, NULL),
(15, 'ValentinaS', 'vale.s@gmail.com', 'viaggiare', '2026-01-28 09:10:49', NULL, NULL, NULL),
(17, 'anninaaaaa18', 'anadiarciuc@gmail.com', 'annina1808', '2026-01-29 11:59:30', 'Ana Maria', 'Diarciuc', '2002-10-10');


ALTER TABLE `libri_biblioterapia`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `reviews`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`),
  ADD UNIQUE KEY `email` (`email`);


ALTER TABLE `libri_biblioterapia`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=88;


ALTER TABLE `reviews`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;


ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
